version: '3.9'

services:
  postgres:
    container_name: 'postgres'
    image: postgres:14.2-alpine
    networks:
      - network
    env_file:
      - .env
    logging:
      driver: none
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    ports:
      - 5432:${POSTGRES_PORT}
networks:
  network:
